### ISSUE TITLE
Не получается затестить код(

### ISSUE THREAD

**Issue by Boyarushnikk** [avel0041/Cyrus-Beck_Alg#2]
Доброго времени суток, хороший человек. Попытался спиздить лабу, не получилось( Подскажи пожалуйста, как запустить её, потому что у меня получается вывести только белый экран.

**Comment by avel0041** [comment]
Ну смотри. Канвас там не большой, поэтому в левом верхнем углу открывшейся страницы на нажатие ЛКМ строится многоугольник. Чтобы завершить его построение нужно сделать дабл клик. Затем можно начать строить отрезки для отсечения. Только сразу предупреждаю, там есть недочёты, например, если построить отрезок внутри многоугольника, то он приложиться до его сторон. 
Ты откуда такой? Тоже Бауманка?

**Comment by Boyarushnikk** [comment]
Спасибо. Я из НовГУ(В городе Великий Новгород), у нас по компьютерной графике запары жесткие. Надо кируса реализовать с мувингом, вращением и масштабированием. А еще 3D куб с RGB освещением, закраской методом Гуро/Фонга без библиотек сторонних. У вас таких заданий не было? Может видел где-то на просторах интернета?

**Comment by avel0041** [comment]
Таких заданий у нас не было, нету и, надеюсь, не будет
